### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by Aswin-TG** [ACrazyNewfie/NameThisSongPlease#2]
Can You Create One Like This For Telegram

**Comment by ACrazyNewfie** [comment]
Hello,

I have already responded to your previous issue. Assuming you missed this, I encourage you to contact me on Twitter @EthanDenny. In future, please refrain from using issues as a way of contacting me, as this is clutters the repository. If you persist, I will block you from the repository.

Thank you.

**Comment by Aswin-TG** [comment]
Sorry sir I haven't seen that conversation .
